export const Signup = 'Signup'
export const SignupUrl = 'https://brytapps.codexnow.com/loginAndRegister/user/signup'
export const SignupFailure = 'SignupFailure'
export const Reset = 'Reset'
export const Login = 'Login'
export const Loginurl = 'https://brytapps.codexnow.com/loginAndRegister/user/login'
export const LoginFailure='LoginFailed'
export const ForgetPasswordurl = 'https://brytapps.codexnow.com/loginAndRegister/user/forgotpassword'
export const ForgetPassword = 'ForgetPassword'
export const isfetching = 'isfetching'
export const SET_LOADING = 'SET_LOADING'
export const islogout  = 'IsLoggedout'
export const LogoutApi = 'https://brytapps.codexnow.com/loginAndRegister/user/profile';
export const GetAllPayeeType = 'Payeetype'
export const GetAllPayeeTypeApi = 'https://brytapps.codexnow.com/loginAndRegister/list/pay/type';
export const GetTypeError='GetTypeERROR'
export const GetAllBanks = 'GetAllBanks'
export const GetAllBanksAPI = 'https://brytapps.codexnow.com/loginAndRegister/list/banks'
export const AddPayeeApi = 'https://brytapps.codexnow.com/loginAndRegister/list/payees'
export const AddPayee = 'AddPayee'
export const FetchPayeeApi = 'https://brytapps.codexnow.com/loginAndRegister/list/payees'
export const FetchPayee='Fetchapi'
export const Deletpayeeapi = 'https://brytapps.codexnow.com/loginAndRegister/get/payee/'
export const UpdateFecthApipayee = 'https://brytapps.codexnow.com/loginAndRegister/get/payee/';
export const AddContactsApi = 'https://brytapps.codexnow.com/loginAndRegister/user/contacts';
export const GetContactsApi = 'https://brytapps.codexnow.com/loginAndRegister/user/contacts';
export const UpdateContactsApi = 'https://brytapps.codexnow.com/loginAndRegister/get/user/contact/';
export const DeleteContactApi = 'https://brytapps.codexnow.com/loginAndRegister/get/user/contact/';
export const GetCountriesApi='https://brytapps.codexnow.com/loginAndRegister/list/countries/codes';